version: "3"
services:
  nuxt:
    container_name: nuxt
    build: src/nuxt
    ports:
      - '80:3000'

  #api:
  #  build: src/api
  #  container_name: api
  #  ports:
  #    - '5000:5000'

  #db:
  #  build: src/db
  #  container_name: db
  #  ports:
  #    - '3306:3306'