version: "3"

services:
  work:
    container_name: Tenshoku
    build: work/
    command: yarn dev
    volumes:
      - ./work:/app
    ports:
      - 3000:3000

  db:
    build: docker/db
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    restart: always
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - "127.0.0.1:3306:3306"
    tty: true