version: "3"

services:
  work:
    container_name: Tenshoku
    build: work/
    command: yarn dev
    volumes:
      - ./work:/app
    ports:
      - 3000:3000

  db:
    build: docker/db
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mydb
    restart: always
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/cnf:/etc/mysql/conf.d
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

  api:
    build: docker/api
    container_name: ex-api
    environment:
      - development
    ports:
      - 5200:5200
    volumes:
      - ./docker/api/src:/src
    command: yarn start