apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nuxt-claim
  labels:
    io.kompose.service: nuxt-claim0
  creationTimestamp: null
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi