apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim
  labels:
    io.kompose.service: db-claim
  creationTimestamp: null
spec:
  storageClassName: db-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi