apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  charset.cnf: |-
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_general_ci
    skip-character-set-client-handshake
    skip-name-resolve
    [client]
    default-character-set=utf8mb4
