apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  serviceName: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      #terminationGracePeriodSeconds: 10
      containers:
      - name: db
        image: ryutaterada/k8s-mariadb
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: db-claim
            mountPath: /var/lib/db
      volumes:
        - name: db-claim
          persistentVolumeClaim:
            claimName: db-claim