apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-volume
  creationTimestamp: null
  labels:
    app: nuxt
spec:
  storageClassName: db-volume
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: data