apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api
    spec:
      containers:
      - image: ryutaterada/k8s-express
        name: api
        ports:
        - containerPort: 5000
        env:
            - name: DB_URL
              value: db://db:3306/user?replicaSet=rs0
            - name: WAIT_HOSTS
              value: db:3306