version: "3.7"

services:
  db:
    container_name: mariadb
    build: docker/db
    volumes:
      - ./docker/db/cnf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306