apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample-node-app
  labels:
    app: sample-node-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-node-app
    spec:
      containers:
        - name: sample-node-app
          image: ryutaterada/k8s-nodejs
          resources:
            limits:
              cpu: "1"
              memory: 1000Mi
          ports:
            - containerPort: 3000
