apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt
  labels:
    app: nuxt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nuxt
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nuxt
    spec:
      containers:
      - name: nuxt
        image: ryutaterada/k8s-nodejs
        resources:
            limits:
              cpu: "1"
              memory: "1000Mi"
        ports:
          - containerPort: 3000