apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nuxt
  name: nuxt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuxt
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nuxt
    spec:
      containers:
      - image: ryutaterada/k8s-nodejs
        name: nuxt
        ports:
          - containerPort: 3000
        env:
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-oauth
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-oauth
                  key: GITHUB_CLIENT_SECRET
            - name: CALLBACK_URL
              value: http://microservice.test/callback
            - name: BASE_URL
              value: http://microservice.test
            - name: NUXT_HOST
              value: 0.0.0.0
            - name: API_SERVICE
              value: http://api-service:3000
      dnsConfig:
        nameservers:
          - 8.8.8.8
        #resources: {}
        # コンテナ側のvolumeディレクトリの設定
        #volumeMounts:
        #  - mountPath: /app
        #    name: nuxt-storage
      #restartPolicy: Always
      # サーバー側のvolumeディレクトリの設定
     #volumes:
        #- name: nuxt-storage
        #  persistentVolumeClaim:
        #    claimName: nuxt-claim
status: {}
